import type { LucideIcon } from "lucide-react";
import {
  User,
  LayoutDashboard,
  Briefcase,
  FileSearch,
  Calendar,
  Bell,
  Settings,
  HelpCircle,
  ChevronRight,
  ChevronUp,
  RefreshCw,
  AlertCircle,
  TriangleAlert,
  Search,
  Filter,
  Columns,
  Plus,
  Menu,
  X,
  Home,
  ScanSearch,
  Network,
  FlaskConical,
  FileCheck,
  BarChart2,
  Minimize2,
  Circle,
  Check,
  Star,
  Eye,
  EyeOff,
  Apple,
} from "lucide-react";

export const Icon: Record<string, LucideIcon> = {
  user: User,
  layoutDashboard: LayoutDashboard,
  briefcase: Briefcase,
  fileSearch: FileSearch,
  calendar: Calendar,
  bell: Bell,
  settings: Settings,
  helpCircle: HelpCircle,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  refreshCw: RefreshCw,
  alertCircle: AlertCircle,
  triangleAlert: TriangleAlert,
  search: Search,
  filter: Filter,
  columns: Columns,
  plus: Plus,
  menu: Menu,
  x: X,
  home: Home,
  scanSearch: ScanSearch,
  network: Network,
  flaskConical: FlaskConical,
  fileCheck: FileCheck,
  fileBarChart: BarChart2,
  minimize2: Minimize2,
  circle: Circle,
  check: Check,
  star: Star,
  eye: Eye,
  eyeOff: EyeOff,
  apple: Apple,
};